### ISSUE TITLE
Freeze fix

### ISSUE THREAD

**Issue by jgan42** [MAGSON-dev/scrumboard#2]
Hi,

I guess you have a problem with your guard (you always redirect the user) + this : 
in login component :
    auth.user$.subscribe((user) => {
      router.navigate(['/']);
    });

Because you always watch the authUser and redirect him to '/' no matter what, and your guard always redirect to '/login', it creates the loop you're stucked in.

Moreover, you need to subscribe in ngOnInit and unsubscribe in ngOnDestroy (because it won't do it itself)

Hope it'll help

**Comment by sondresorbye0111** [comment]
I fixed the guard by returning true: 
`canActivate(route, state: RouterStateSnapshot) {
    return this.auth.user$.map(user => {
      // if the user is signed in
      console.log({user});
      if (user) { return true; }
      this.router.navigate(['/login'], {
        queryParams: { returnUrl: state.url }
      });

      // if the user is not signed in
      return false;
    });
  }`
but it does still freeze. It logs unlimited user objects. 
![image](https://user-images.githubusercontent.com/22012669/42240124-91fa06e4-7f06-11e8-8205-39b43b4a9f20.png)

**Comment by sondresorbye0111** [comment]
I also tried to unsubscribe to all subscriptions in ngOnDestroy(), still freezing :(
I also tried to remove all the user objects by adding .take(1) to the user$ observable, like this: 
`return this.auth.user$.take(1).map(user => {
      // if the user is signed in
      console.log({user}, 'freeze');
      if (user) { return true; }
      this.router.navigate(['/login'], {
        queryParams: { returnUrl: state.url }
      });

      // if the user is not signed in
      return false;
    });`
it still does not work

**Comment by sondresorbye0111** [comment]
I fixed the issue. The problem was in the routerModule configuration. So the guard made a loop to itself. Thank you
